# Generated by Django 3.2.18 on 2024-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
