# Generated by Django 3.2.18 on 2024-01-22 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(unique=True)),
                ('view_count', models.IntegerField(default=0)),
                ('letter_count', models.IntegerField(default=0)),
            ],
        ),
    ]
