# Generated by Django 3.2.18 on 2024-01-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='view_count',
        ),
    ]
