# Generated by Django 3.2.18 on 2023-11-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
    ]
