# Generated by Django 3.2.18 on 2023-11-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_customuser_agree_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='character',
            field=models.CharField(choices=[('charater1', '하트'), ('charater2', '동룰'), ('charater3', '크리스마스')], default='charater1', max_length=20),
        ),
    ]
