# Generated by Django 3.2.18 on 2024-02-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_receive_notification',
        ),
    ]
