# Generated by Django 3.2.18 on 2023-11-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_alter_customuser_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='character',
            field=models.CharField(choices=[('character1', '하트'), ('character2', '동룰'), ('character3', '크리스마스')], default='character1', max_length=20),
        ),
    ]
