# Generated by Django 3.2.18 on 2023-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_alter_customuser_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='character',
            field=models.CharField(choices=[('character1', 'heart'), ('character2', 'animal'), ('character3', 'winter'), ('character4', 'autumn')], default='character1', max_length=20),
        ),
    ]
