# Generated by Django 3.2.18 on 2023-11-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_contentapp', '0002_alter_letter_content_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_content',
            name='tema',
            field=models.CharField(choices=[('blue', '블루'), ('pink', '핑크'), ('gray', '그레이'), ('yellow', '옐로우'), ('green', '그린'), ('purple', '퍼플')], default='pink', max_length=20),
        ),
    ]
