# Generated by Django 3.2.18 on 2023-11-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_contentapp', '0004_alter_letter_content_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter_content',
            name='tema',
        ),
    ]
