# Generated by Django 3.2.18 on 2023-11-08 21:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter_info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('receiver_name', models.CharField(max_length=10, null=True)),
                ('written_at', models.DateField(null=True)),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter_info', to='letterapp.letter')),
            ],
        ),
    ]
