# Generated by Django 3.2.18 on 2023-11-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_infoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_info',
            name='receiver_name',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='letter_info',
            name='sender_name',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
