# Generated by Django 3.2.18 on 2023-11-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_infoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_info',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
