# Generated by Django 3.2.18 on 2024-03-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voca',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voca', to=settings.AUTH_USER_MODEL),
        ),
    ]
