# Generated by Django 3.2.18 on 2023-11-15 10:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_quiz',
            name='choiceanswer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('보기1', '✓'), ('보기2', '✓'), ('보기3', '✓')], max_length=50, null=True),
        ),
    ]
