# Generated by Django 3.2.18 on 2023-11-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_quiz',
            name='answer',
            field=models.TextField(max_length=51, null=True),
        ),
    ]
