# Generated by Django 3.2.18 on 2023-11-19 12:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_quizapp', '0002_alter_letter_quiz_answer_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_quiz',
            name='choiceanswer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('choice1', '✓'), ('choice2', '✓'), ('choice3', '✓')], max_length=50, null=True),
        ),
    ]
