# Generated by Django 3.2.18 on 2023-11-08 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('progress', models.CharField(choices=[('progress1', 'progress1'), ('progress2', 'progress2'), ('progress3', 'progress3'), ('done', 'done')], default='progress1', max_length=20)),
                ('qr', models.ImageField(upload_to='letter/')),
                ('url', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=6, unique=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
