# Generated by Django 3.2.18 on 2023-12-06 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 20, 13, 32, 900070)),
        ),
    ]
