# Generated by Django 3.2.18 on 2023-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='state',
            field=models.CharField(choices=[('unchecked', '미확인'), ('checked', '확인 완료'), ('saved', '저장 완료'), ('unsaved', '저장 취소')], default='unchecked', max_length=20),
        ),
    ]
