# Generated by Django 3.2.18 on 2023-12-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_letter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
