# Generated by Django 3.2.18 on 2023-11-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_alter_letter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_unsaved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='state',
            field=models.CharField(choices=[('unchecked', '미확인'), ('checked', '확인 완료'), ('saved', '저장 완료')], default='unchecked', max_length=20),
        ),
    ]
