# Generated by Django 3.2.18 on 2023-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_alter_letter_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='checked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
