# Generated by Django 3.2.18 on 2023-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0003_auto_20231116_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='error',
            field=models.IntegerField(default=0),
        ),
    ]
