# Generated by Django 3.2.18 on 2023-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0004_letter_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='locked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
