# Generated by Django 3.2.18 on 2023-11-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0004_remove_letter_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
