# Generated by Django 3.2.18 on 2023-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0005_letter_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
