# Generated by Django 3.2.18 on 2023-11-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0006_letter_is_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='locked_at',
            new_name='errored_at',
        ),
    ]
