# Generated by Django 3.2.18 on 2023-11-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0007_rename_locked_at_letter_errored_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='is_locked',
        ),
    ]
