# Generated by Django 3.2.18 on 2023-11-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0007_auto_20231111_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='received_at',
        ),
    ]
